### ISSUE TITLE
Can't make an Android build because UnityEditor used in MonoBeahviour components.

### ISSUE THREAD

**Issue by robbgray** [cmacmillan/CurveDesigner#1]
I think you did a great job but I don't see how you can use these curves unless you bake them into a build. All the curve components require UnityEditor and doesn't seem to be trivial to remove those dependencies.

**Comment by cmacmillan** [comment]
Thanks for the feedback. I actually just fixed this in f1c9d6d10fba64331f2e710824f9e118b73d5d60 after another user reported it. Unfortunately there is a ~one week review period before I can update the asset on the asset store.

**Comment by robbgray** [comment]
Great thanks. Yeah lots of ifdefs. I think there's a solution with assemblies but that would have required a lot of moving code around too so thanks for doing this.

**Comment by cmacmillan** [comment]
Yeah the main issue is that I use a retained-ish method of doing the UI. I store the root object of this retained widget tree on the Curve3D object, so I can't put the whole widget tree in the Assembly-CSharp-Editor pass because then Curve3D wouldn't be able to keep a reference to the widget tree.
